simplify repo_sync

diff --git a/repo_sync b/repo_sync
--- a/repo_sync
+++ b/repo_sync
@@ -1,21 +1,16 @@
 #!/usr/bin/env bash
 
-if [ -z "$1" ] ; then
-    action='pull'
-else
-    action="$1"
-fi
-
 function needful () {
-    local action="$1"
-    local repo="$(dirname $2)"
+    local repo="$(dirname $1)"
     (
         cd $repo
         current="$(git branch | awk '/^\*/ { print $2}')"
         [ "$current" == "master" ] || git checkout master &> /dev/null
         git fetch --tags &> /dev/null
-        git $action origin master &> /dev/null \
+        git pull origin master &> /dev/null \
             || echo "Error! Failed to pull $repo"
+        git submodule update --init &> /dev/null \
+            || echo "Error! Failed to update submodules for $repo"
         [ "$current" == "master" ] || git checkout $current &> /dev/null
     )
 }
@@ -31,4 +26,4 @@ fi
 # Make sure SSH key is loaded before kicking off workers
 ssh git@github.com &>/dev/null
 
-find . -type d -name '.git' | xargs -n1 -P$PARALLEL -I{} bash -c "needful $action {}"
+find . -type d -name '.git' | xargs -n1 -P$PARALLEL -I{} bash -c "needful {}"
