support actions for repo_sync

diff --git a/repo_sync b/repo_sync
--- a/repo_sync
+++ b/repo_sync
@@ -1,9 +1,15 @@
 #!/usr/bin/env bash
 
 if [ -z "$1" ] ; then
+    action='pull'
+else
+    action="$1"
+fi
+
+if [ -z "$2" ] ; then
     repoPath="$(pwd)"
 else
-    repoPath="$1"
+    repoPath="$2"
 fi
 
 for repo in $repoPath/* ; do 
@@ -13,7 +19,7 @@ for repo in $repoPath/* ; do
             cd $repo
             current="$(git branch | awk '/^*/ { print $2}')"
             [ "$current" == "master" ] || git checkout master &> /dev/null
-            git pull origin master &> /dev/null || echo "Error! Failed to pull repo"
+            git $action origin master &> /dev/null || echo "Error! Failed to pull repo"
             [ "$current" == "master" ] || git checkout $currentBranch &> /dev/null
         )
     fi
